export * from './layout/Layout';
export * from './record/RecordPlayer';
export * from './menu-app-bar/MenuAppBar';
export * from './menu-app-bar/ToggleThemeSetting'
export * from './menu-app-bar/LanguageSetting';
export * from './menu-app-bar/MenuItemAppBar';
export * from './menu-app-bar/SpeechOrText';
export * from './sobre/EstudeImageList';
export * from './sobre/PaperSobre'
export * from './sobre/Motivacao';
export * from './sobre/Proposta';
export * from './text-translate/TextTranslate';